"use client";
import { useState } from "react";

export default function Home() {
  const [file, setFile] = useState<File | null>(null);
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      setFile(e.target.files[0]);
      setResult(null);
    }
  };

  const handleUpload = async () => {
    if (!file) return;

    setLoading(true);
    const formData = new FormData();
    formData.append("file", file);
    //https://voice-deepfake-detection-backend.onrender.com
    //http://localhost:8000/predict 
    try {
      const response = await fetch("http://localhost:8000/predict", {
        method: "POST",
        body: formData,
      });
      const data = await response.json();
      setResult(data);
    } catch (error) {
      console.error("Error:", error);
      alert("Backend connection failed.");
    }
    setLoading(false);
  };

  return (
    <main className="flex min-h-screen flex-col items-center justify-center bg-gray-900 text-white p-6">
      <div className="bg-gray-800 p-8 rounded-2xl shadow-2xl max-w-3xl w-full border border-gray-700">
        <h1 className="text-3xl font-bold mb-2 text-center text-blue-400">
          🎙️ VoiceGuard AI
        </h1>
        <p className="text-gray-400 text-center mb-8">
          Deep Forensic Spectrogram Analysis
        </p>

        {/* Upload Box */}
        <div className="mb-6">
          <input
            type="file"
            accept=".wav,.mp3"
            onChange={handleFileChange}
            className="block w-full text-sm text-gray-400 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-600 file:text-white hover:file:bg-blue-700 cursor-pointer"
          />
        </div>

        {/* Analyze Button */}
        <button
          onClick={handleUpload}
          disabled={!file || loading}
          className={`w-full py-3 rounded-lg font-bold transition-all ${
            loading
              ? "bg-gray-600 cursor-not-allowed"
              : "bg-blue-500 hover:bg-blue-600 shadow-lg shadow-blue-500/30"
          }`}
        >
          {loading ? "Analyzing Audio Physics..." : "Generate Forensic Report"}
        </button>

        {/* RESULTS SECTION */}
        {result && (
          <div className={`mt-8 p-6 rounded-xl border ${
            result.result === "REAL_HUMAN" 
              ? "bg-green-900/20 border-green-500" 
              : "bg-red-900/20 border-red-500"
          }`}>
            <div className="text-center mb-6">
              <h2 className={`text-3xl font-bold mb-2 ${
                result.result === "REAL_HUMAN" ? "text-green-400" : "text-red-400"
              }`}>
                {result.result === "REAL_HUMAN" ? "👤 REAL HUMAN" : "🤖 AI GENERATED"}
              </h2>
              <p className="text-gray-300">
                Confidence: <span className="font-bold text-white">{result.confidence}</span>
              </p>
            </div>

            {/* VISUAL EVIDENCE (The Spectrogram) */}
            <div className="bg-black p-2 rounded-lg border border-gray-600">
               <h3 className="text-gray-400 text-sm font-bold mb-2 uppercase tracking-wider text-center">
                 Visual Evidence: Mel-Spectrogram
               </h3>
               {/* This displays the image generated by Python */}
               <img 
                  src={`data:image/png;base64,${result.spectrogram}`} 
                  alt="Forensic Spectrogram" 
                  className="w-full h-auto rounded-md"
                />
            </div>
            
            <div className="mt-4 text-xs text-gray-400 bg-gray-900/50 p-3 rounded">
                <p><strong>How to read this graph:</strong></p>
                <ul className="list-disc pl-5 mt-1 space-y-1">
                    <li><strong>Bright Colors (Yellow/Red):</strong> High energy/loudness.</li>
                    <li><strong>Dark Colors (Blue/Black):</strong> Silence or lack of sound.</li>
                    <li><strong>If REAL:</strong> Look for "messy" organic textures and gradual curves.</li>
                    <li><strong>If AI:</strong> Look for "checkerboard" patterns, unnatural grid lines, or hard cut-offs in the top frequencies.</li>
                </ul>
            </div>

          </div>
        )}
      </div>
    </main>
  );
}